# Generated by Django 4.0.1 on 2022-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_imgs')),
                ('discount_deal', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
