# Generated by Django 4.0.1 on 2022-06-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_banner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.main_category')),
            ],
        ),
        migrations.CreateModel(
            name='subsub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sub_category')),
            ],
        ),
    ]
