# Generated by Django 4.0.1 on 2022-06-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_main_category_sub_category_subsub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('featured_image', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=100)),
                ('discount', models.IntegerField(max_length=200)),
                ('product_info', models.TextField()),
                ('model_name', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('s_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section'),
        ),
        migrations.CreateModel(
            name='additional_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
