# Generated by Django 4.0.1 on 2022-07-01 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp1name', models.CharField(max_length=100, null=True)),
                ('comp1desig', models.CharField(max_length=100, null=True)),
                ('comp1sal', models.CharField(max_length=100, null=True)),
                ('comp1dura', models.CharField(max_length=100, null=True)),
                ('comp2name', models.CharField(max_length=100, null=True)),
                ('comp2desig', models.CharField(max_length=100, null=True)),
                ('comp2sal', models.CharField(max_length=100, null=True)),
                ('comp2dura', models.CharField(max_length=100, null=True)),
                ('comp3name', models.CharField(max_length=100, null=True)),
                ('comp3desig', models.CharField(max_length=100, null=True)),
                ('comp3sal', models.CharField(max_length=100, null=True)),
                ('comp3dura', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursepg', models.CharField(max_length=100, null=True)),
                ('schoolclgpg', models.CharField(max_length=200, null=True)),
                ('yearpasspg', models.CharField(max_length=20, null=True)),
                ('percentpg', models.CharField(max_length=30, null=True)),
                ('coursegra', models.CharField(max_length=100, null=True)),
                ('schoolclggra', models.CharField(max_length=200, null=True)),
                ('yearpassgra', models.CharField(max_length=20, null=True)),
                ('percentgra', models.CharField(max_length=30, null=True)),
                ('coursesc', models.CharField(max_length=100, null=True)),
                ('schoolclgsc', models.CharField(max_length=200, null=True)),
                ('yearpasssc', models.CharField(max_length=20, null=True)),
                ('percentsc', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
