# Generated by Django 4.0.5 on 2022-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(upload_to='media/empimages'),
        ),
    ]
