# Generated by Django 4.0.5 on 2022-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='media/empimages'),
        ),
    ]
