# Generated by Django 4.0.5 on 2022-07-24 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0005_alter_employeeimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('totalDays', models.CharField(max_length=20, null=True)),
                ('comments', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
