# Generated by Django 4.0.5 on 2022-07-24 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0006_leaves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leaves',
            new_name='employeeLeave',
        ),
    ]
