# Generated by Django 4.0.5 on 2022-07-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_comments_employeeleave_commentsreasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='FIN',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='SSN',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='fathersname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='passport',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
