# Generated by Django 4.0.5 on 2022-08-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeedetails_fin_employeedetails_ssn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='leavesAlloted',
            field=models.IntegerField(null=True),
        ),
    ]
